/**
 * Shared lexicons for Writing Insights (routes still live under /brain-science).
 *
 * These are exploratory token lists, not psychology. Spanish is included because
 * ~1 in 8 published posts is ES-only and JS `\b` never matched accented words.
 *
 * Keep lists high-signal. Do not add topic words (leadership, puerto, children)
 * to affect lists — those belong in tags/themes.
 */

function freezeList(words: string[]): readonly string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const word of words) {
    const normalized = word.toLowerCase().trim();
    if (!normalized || seen.has(normalized)) continue;
    seen.add(normalized);
    out.push(normalized);
  }
  return out;
}

/** Affect tokens for intensity charts (insights + patterns + emotional-post counts). */
export const EMOTIONAL_WORDS = freezeList([
  // EN
  'love',
  'hate',
  'fear',
  'joy',
  'sadness',
  'anger',
  'peace',
  'anxiety',
  'hope',
  'despair',
  'gratitude',
  'frustration',
  'excited',
  'worried',
  'confused',
  'inspired',
  'overwhelmed',
  'content',
  'restless',
  'fulfilled',
  'grief',
  'shame',
  'guilt',
  'rage',
  'loneliness',
  'lonely',
  'tenderness',
  'mercy',
  'compassion',
  'empathy',
  'dignity',
  'pride',
  'trust',
  'courage',
  'relief',
  'panic',
  'dread',
  'sorrow',
  'numb',
  'exhausted',
  'bitter',
  'resentment',
  'tenderness',
  'serenity',
  'warmth',
  'grief',
  // ES
  'amor',
  'odio',
  'miedo',
  'alegría',
  'alegria',
  'tristeza',
  'ira',
  'paz',
  'ansiedad',
  'esperanza',
  'desesperación',
  'desesperacion',
  'gratitud',
  'frustración',
  'frustracion',
  'orgullo',
  'ternura',
  'compasión',
  'compasion',
  'empatía',
  'empatia',
  'dignidad',
  'vergüenza',
  'verguenza',
  'culpa',
  'duelo',
  'soledad',
  'rabia',
  'pánico',
  'panico',
  'angustia',
  'alivio',
  'confianza',
  'valentía',
  'valentia',
  'resentimiento',
  'agotado',
  'vacío',
  'vacio',
  'daño',
  'dano',
]);

/** First-person struggle / exposure — not hedge words (maybe, sometimes). */
export const VULNERABILITY_WORDS = freezeList([
  'struggle',
  'difficult',
  'challenge',
  'pain',
  'hurt',
  'broken',
  'healing',
  'recovery',
  'vulnerable',
  'afraid',
  'scared',
  'nervous',
  'uncertain',
  'doubt',
  'ashamed',
  'grieving',
  'lonely',
  'exhausted',
  'helpless',
  'fragile',
  'exposed',
  'tender',
  'tears',
  'crying',
  'admit',
  'forgive',
  'apology',
  'unsure',
  'failing',
  'lucha',
  'dolor',
  'herida',
  'roto',
  'sanar',
  'vulnerable',
  'miedo',
  'asustado',
  'incierto',
  'duda',
  'vergüenza',
  'verguenza',
  'agotado',
  'frágil',
  'fragil',
  'lágrimas',
  'lagrimas',
  'perdón',
  'perdon',
  'admitir',
]);

/** Agency / conviction tokens. Avoid ultra-common "know". */
export const CONFIDENCE_WORDS = freezeList([
  'believe',
  'certain',
  'sure',
  'confident',
  'clear',
  'understand',
  'realize',
  'discover',
  'practice',
  'master',
  'achieve',
  'succeed',
  'committed',
  'disciplined',
  'accountable',
  'responsible',
  'capable',
  'willing',
  'refuse',
  'boundaries',
  'evidence',
  'named',
  'owned',
  'creo',
  'seguro',
  'cierta',
  'cierto',
  'confiado',
  'claro',
  'entiendo',
  'comprendo',
  'descubrir',
  'práctica',
  'practica',
  'lograr',
  'comprometido',
  'responsable',
  'capaz',
  'dispuesto',
  'límites',
  'limites',
  'evidencia',
]);

/** Discourse markers that proxy argument structure, not IQ. */
export const INTELLECTUAL_WORDS = freezeList([
  'because',
  'therefore',
  'however',
  'although',
  'nevertheless',
  'furthermore',
  'moreover',
  'consequently',
  'thus',
  'hence',
  'accordingly',
  'similarly',
  'conversely',
  'meanwhile',
  'subsequently',
  'previously',
  'initially',
  'ultimately',
  'fundamentally',
  'essentially',
  'instead',
  'rather',
  'specifically',
  'whereas',
  'nonetheless',
  'porque',
  'aunque',
  'sin embargo',
  'por tanto',
  'por lo tanto',
  'además',
  'ademas',
  'entonces',
  'mientras',
  'después',
  'despues',
  'antes',
  'finalmente',
  'esencialmente',
  'en cambio',
  'no obstante',
  'básicamente',
  'basicamente',
]);

export const CURIOSITY_WORDS = freezeList([
  'wonder',
  'curious',
  'question',
  'explore',
  'discover',
  'investigate',
  'examine',
  'analyze',
  'study',
  'research',
  'learn',
  'understand',
  'figure out',
  'find out',
  'look into',
  'dive into',
  'uncover',
  'reveal',
  'unveil',
  'me pregunto',
  'curioso',
  'pregunta',
  'preguntar',
  'explorar',
  'descubrir',
  'investigar',
  'examinar',
  'analizar',
  'estudiar',
  'aprender',
  'entender',
  'averiguar',
  'indagar',
]);

export const WISDOM_WORDS = freezeList([
  'experience',
  'learned',
  'realized',
  'understood',
  'discovered',
  'came to',
  'figured out',
  'worked out',
  'determined',
  'concluded',
  'decided',
  'chose',
  'preferred',
  'valued',
  'appreciated',
  'recognized',
  'acknowledged',
  'looking back',
  'in hindsight',
  'used to',
  'no longer',
  'experiencia',
  'aprendí',
  'aprendi',
  'me di cuenta',
  'entendí',
  'entendi',
  'descubrí',
  'descubri',
  'concluí',
  'conclui',
  'decidí',
  'decidi',
  'elegí',
  'elegi',
  'valoré',
  'valore',
  'reconocí',
  'reconoci',
  'ya no',
]);

/**
 * Coarse post-level buckets. "Neutral" is cognitive/reflective verbs, not
 * emotionally flat prose. Spanish included so ES posts can vote.
 */
export const SENTIMENT_WORDS = {
  positive: freezeList([
    'love',
    'joy',
    'excited',
    'happy',
    'grateful',
    'inspired',
    'confident',
    'proud',
    'accomplished',
    'fulfilled',
    'peaceful',
    'content',
    'optimistic',
    'hopeful',
    'energized',
    'motivated',
    'successful',
    'achieved',
    'appreciate',
    'celebrate',
    'thrilled',
    'delighted',
    'blessed',
    'empowered',
    'liberated',
    'serene',
    'tranquil',
    'harmonious',
    'mercy',
    'compassion',
    'empathy',
    'dignity',
    'tenderness',
    'courage',
    'trust',
    'relief',
    'grace',
    'kindness',
    'patience',
    'humility',
    'belonging',
    'amor',
    'alegría',
    'alegria',
    'feliz',
    'agradecido',
    'paz',
    'esperanza',
    'orgullo',
    'gratitud',
    'cariño',
    'carino',
    'ternura',
    'dignidad',
    'respeto',
    'libertad',
    'valentía',
    'valentia',
    'confianza',
    'serenidad',
    'alivio',
    'compasión',
    'compasion',
    'empatía',
    'empatia',
    'misericordia',
    'calidez',
    'paciencia',
    'humildad',
  ]),
  negative: freezeList([
    'hate',
    'fear',
    'sadness',
    'anger',
    'anxiety',
    'despair',
    'frustration',
    'worried',
    'confused',
    'overwhelmed',
    'restless',
    'pain',
    'hurt',
    'broken',
    'struggle',
    'failure',
    'disappointed',
    'defeated',
    'hopeless',
    'stuck',
    'trapped',
    'suffering',
    'dread',
    'terror',
    'panic',
    'distress',
    'agony',
    'torment',
    'misery',
    'anguish',
    'grief',
    'sorrow',
    'regret',
    'shame',
    'guilt',
    'humiliation',
    'isolation',
    'rage',
    'lonely',
    'loneliness',
    'resentment',
    'exhaustion',
    'burnout',
    'helpless',
    'powerless',
    'numb',
    'cruelty',
    'odio',
    'miedo',
    'tristeza',
    'ira',
    'ansiedad',
    'desesperación',
    'desesperacion',
    'frustración',
    'frustracion',
    'dolor',
    'herida',
    'roto',
    'lucha',
    'culpa',
    'vergüenza',
    'verguenza',
    'duelo',
    'soledad',
    'rabia',
    'pánico',
    'panico',
    'angustia',
    'arrepentimiento',
    'aislamiento',
    'agotado',
    'vacío',
    'vacio',
    'amargo',
    'daño',
    'dano',
    'fracaso',
    'sufrimiento',
  ]),
  neutral: freezeList([
    'think',
    'believe',
    'understand',
    'realize',
    'observe',
    'notice',
    'consider',
    'reflect',
    'analyze',
    'examine',
    'study',
    'learn',
    'discover',
    'explore',
    'investigate',
    'research',
    'determine',
    'conclude',
    'decide',
    'evaluate',
    'assess',
    'review',
    'acknowledge',
    'recognize',
    'identify',
    'describe',
    'explain',
    'clarify',
    'define',
    'pensar',
    'creo',
    'entender',
    'comprender',
    'darme cuenta',
    'me doy cuenta',
    'observar',
    'notar',
    'considerar',
    'reflexionar',
    'analizar',
    'examinar',
    'estudiar',
    'aprender',
    'descubrir',
    'explorar',
    'investigar',
    'concluir',
    'decidir',
    'evaluar',
    'reconocer',
    'identificar',
    'describir',
    'explicar',
    'aclarar',
    'definir',
  ]),
} as const;

export const GROWTH_TAGS = freezeList([
  'personal-growth',
  'transformation',
  'healing',
  'self-improvement',
  'learning',
  'consciousness',
  'recovery',
  'inner-work',
]);

export const GROWTH_KEYWORDS = freezeList([
  'growth',
  'change',
  'transform',
  'learn',
  'evolve',
  'improve',
  'heal',
  'discover',
  'crecimiento',
  'cambiar',
  'transformar',
  'aprender',
  'evolucionar',
  'mejorar',
  'sanar',
  'descubrir',
]);
