// Auto-generated by scripts/generate-social-images.js. DO NOT EDIT BY HAND.
export const SOCIAL_IMAGE_MANIFEST: Record<string, string> = {
  '/images/2025/broken-signals.avif':
    '/social/images/2025/broken-signals-social.jpg',
  '/images/2025/hands-touching-each-other.avif':
    '/social/images/2025/hands-touching-each-other-social.jpg',
  '/images/2025/intelligence-burn.avif':
    '/social/images/2025/intelligence-burn-social.jpg',
  '/images/2025/intelligence-burns-conversation.avif':
    '/social/images/2025/intelligence-burns-conversation-social.jpg',
  '/images/2025/light-and-shadow.avif':
    '/social/images/2025/light-and-shadow-social.jpg',
  '/images/2025/line-on-sand.avif':
    '/social/images/2025/line-on-sand-social.jpg',
  '/images/2025/on-doom-scrolling.avif':
    '/social/images/2025/on-doom-scrolling-social.jpg',
  '/images/2025/shadows.avif': '/social/images/2025/shadows-social.jpg',
  '/images/2025/the-prometheus-problem.avif':
    '/social/images/2025/the-prometheus-problem-social.jpg',
  '/images/2025/trillion.avif': '/social/images/2025/trillion-social.jpg',
  '/images/2026/arithmetic.avif': '/social/images/2026/arithmetic-social.jpg',
  '/images/2026/control.avif': '/social/images/2026/control-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260319210335.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260319210335-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260319210358.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260319210358-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260319222041.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260319222041-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260320221404.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260320221404-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260320230323.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260320230323-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260321093358.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260321093358-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260324135646.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260324135646-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260324185951.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260324185951-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260324212054.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260324212054-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260325214228.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260325214228-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260326140331.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260326140331-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260326140722.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260326140722-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260327125905.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260327125905-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260327144134.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260327144134-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260327144322.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260327144322-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260327211316.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260327211316-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260327211331.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260327211331-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260327211342.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260327211342-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260328124743.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260328124743-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260328132403.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260328132403-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260328140556.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260328140556-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260329140823.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260329140823-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260329140825.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260329140825-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260329194819.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260329194819-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260402162156.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260402162156-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260402170524.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260402170524-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260404145925.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260404145925-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260404150136.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260404150136-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260404150156.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260404150156-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260404150602.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260404150602-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260404150620.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260404150620-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260406080722.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260406080722-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260406124619.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260406124619-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260406140908.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260406140908-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260406143257.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260406143257-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260406143800.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260406143800-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260408193925.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260408193925-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260413195125.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260413195125-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260414164603.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260414164603-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260415141056.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260415141056-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260416083607.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260416083607-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260417153645.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260417153645-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260417164435.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260417164435-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260418073224.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260418073224-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260418151044.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260418151044-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260419081550.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260419081550-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260420105214.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260420105214-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260422183844.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260422183844-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260422193700.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260422193700-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260423100846.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260423100846-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260423131600.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260423131600-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260423131603.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260423131603-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260423131606.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260423131606-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260423131616.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260423131616-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260423150807.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260423150807-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260424214818.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260424214818-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260426150625.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260426150625-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260428102557.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260428102557-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260428102923.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260428102923-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260428114546.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260428114546-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260428114559.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260428114559-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260428122738.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260428122738-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260428122807.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260428122807-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260428123621.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260428123621-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260429080712.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260429080712-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260429080718.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260429080718-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260429080724.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260429080724-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260429080733.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260429080733-social.jpg',
  '/images/2026/crimson-desert-review/Crimson Desert_20260429081024.avif':
    '/social/images/2026/crimson-desert-review/Crimson Desert_20260429081024-social.jpg',
  '/images/2026/cupey-papi.avif': '/social/images/2026/cupey-papi-social.jpg',
  '/images/2026/dispatch-review/dispatch-logo-screen.avif':
    '/social/images/2026/dispatch-review/dispatch-logo-screen-social.jpg',
  '/images/2026/dispatch-review/dispatch-pc-game-dispatch.avif':
    '/social/images/2026/dispatch-review/dispatch-pc-game-dispatch-social.jpg',
  '/images/2026/empathy-and-compassion.avif':
    '/social/images/2026/empathy-and-compassion-social.jpg',
  '/images/2026/escaping-the-feeds.avif':
    '/social/images/2026/escaping-the-feeds-social.jpg',
  '/images/2026/fasting-hurts.avif':
    '/social/images/2026/fasting-hurts-social.jpg',
  '/images/2026/friendly-ai.avif': '/social/images/2026/friendly-ai-social.jpg',
  '/images/2026/in-my-feelings.avif':
    '/social/images/2026/in-my-feelings-social.jpg',
  '/images/2026/learning.avif': '/social/images/2026/learning-social.jpg',
  '/images/2026/lemon-pepper-chicken-tais.avif':
    '/social/images/2026/lemon-pepper-chicken-tais-social.jpg',
  '/images/2026/neverending-walk.avif':
    '/social/images/2026/neverending-walk-social.jpg',
  '/images/2026/notes-on-respect.avif':
    '/social/images/2026/notes-on-respect-social.jpg',
  '/images/2026/oh-fuck.avif': '/social/images/2026/oh-fuck-social.jpg',
  '/images/2026/on-leadership-plus.avif':
    '/social/images/2026/on-leadership-plus-social.jpg',
  '/images/2026/simplicity.avif': '/social/images/2026/simplicity-social.jpg',
  '/images/2026/the-abyss.avif': '/social/images/2026/the-abyss-social.jpg',
  '/images/2026/the-dark-abyss.avif':
    '/social/images/2026/the-dark-abyss-social.jpg',
  '/images/2026/the-work-never-ends.avif':
    '/social/images/2026/the-work-never-ends-social.jpg',
  '/images/2026/tinkering-in-2026.avif':
    '/social/images/2026/tinkering-in-2026-social.jpg',
  '/images/2026/value-roads.avif': '/social/images/2026/value-roads-social.jpg',
  '/images/ai-is-creepy.avif': '/social/images/ai-is-creepy-social.jpg',
  '/images/anime-souls.avif': '/social/images/anime-souls-social.jpg',
  '/images/breathing-deep.avif': '/social/images/breathing-deep-social.jpg',
  '/images/cattoo.avif': '/social/images/cattoo-social.jpg',
  '/images/default_covers/default-1.avif':
    '/social/images/default_covers/default-1-social.jpg',
  '/images/default_covers/default-10.avif':
    '/social/images/default_covers/default-10-social.jpg',
  '/images/default_covers/default-2.avif':
    '/social/images/default_covers/default-2-social.jpg',
  '/images/default_covers/default-3.avif':
    '/social/images/default_covers/default-3-social.jpg',
  '/images/default_covers/default-4.avif':
    '/social/images/default_covers/default-4-social.jpg',
  '/images/default_covers/default-5.avif':
    '/social/images/default_covers/default-5-social.jpg',
  '/images/default_covers/default-6.avif':
    '/social/images/default_covers/default-6-social.jpg',
  '/images/default_covers/default-7.avif':
    '/social/images/default_covers/default-7-social.jpg',
  '/images/default_covers/default-8.avif':
    '/social/images/default_covers/default-8-social.jpg',
  '/images/default_covers/default-9.avif':
    '/social/images/default_covers/default-9-social.jpg',
  '/images/default_covers/wizards666_easy_clouds_--chaos_70_--ar_32_--weird_900_--v_7_944cbbcd-64a7-463b-b2c8-936dbe3e07f7_2.avif':
    '/social/images/default_covers/wizards666_easy_clouds_--chaos_70_--ar_32_--weird_900_--v_7_944cbbcd-64a7-463b-b2c8-936dbe3e07f7_2-social.jpg',
  '/images/default_covers/wizards666_explore_infinity_and_chaos_--chaos_70_--ar_32_--we_946a9dac-b5c1-477b-b06f-2c43b810ffef_2.avif':
    '/social/images/default_covers/wizards666_explore_infinity_and_chaos_--chaos_70_--ar_32_--we_946a9dac-b5c1-477b-b06f-2c43b810ffef_2-social.jpg',
  '/images/default-divider.avif': '/social/images/default-divider-social.jpg',
  '/images/default.avif': '/social/images/default-social.jpg',
  '/images/empathy.avif': '/social/images/empathy-social.jpg',
  '/images/evs/ev-ai-images_10.avif':
    '/social/images/evs/ev-ai-images_10-social.jpg',
  '/images/evs/ev-ai-images_11.avif':
    '/social/images/evs/ev-ai-images_11-social.jpg',
  '/images/evs/ev-ai-images_12.avif':
    '/social/images/evs/ev-ai-images_12-social.jpg',
  '/images/evs/ev-ai-images_13.avif':
    '/social/images/evs/ev-ai-images_13-social.jpg',
  '/images/evs/ev-ai-images_14.avif':
    '/social/images/evs/ev-ai-images_14-social.jpg',
  '/images/evs/ev-ai-images_15.avif':
    '/social/images/evs/ev-ai-images_15-social.jpg',
  '/images/evs/ev-ai-images_16.avif':
    '/social/images/evs/ev-ai-images_16-social.jpg',
  '/images/evs/ev-ai-images_17.avif':
    '/social/images/evs/ev-ai-images_17-social.jpg',
  '/images/evs/ev-ai-images_18.avif':
    '/social/images/evs/ev-ai-images_18-social.jpg',
  '/images/evs/ev-ai-images_19.avif':
    '/social/images/evs/ev-ai-images_19-social.jpg',
  '/images/evs/ev-ai-images_20.avif':
    '/social/images/evs/ev-ai-images_20-social.jpg',
  '/images/evs/ev-ai-images_21.avif':
    '/social/images/evs/ev-ai-images_21-social.jpg',
  '/images/evs/ev-ai-images_22.avif':
    '/social/images/evs/ev-ai-images_22-social.jpg',
  '/images/evs/ev-ai-images_23.avif':
    '/social/images/evs/ev-ai-images_23-social.jpg',
  '/images/evs/ev-ai-images_24.avif':
    '/social/images/evs/ev-ai-images_24-social.jpg',
  '/images/evs/ev-ai-images_25.avif':
    '/social/images/evs/ev-ai-images_25-social.jpg',
  '/images/evs/ev-ai-images_26.avif':
    '/social/images/evs/ev-ai-images_26-social.jpg',
  '/images/evs/ev-ai-images_27.avif':
    '/social/images/evs/ev-ai-images_27-social.jpg',
  '/images/evs/ev-ai-images_28.avif':
    '/social/images/evs/ev-ai-images_28-social.jpg',
  '/images/evs/ev-ai-images_29.avif':
    '/social/images/evs/ev-ai-images_29-social.jpg',
  '/images/evs/ev-ai-images_30.avif':
    '/social/images/evs/ev-ai-images_30-social.jpg',
  '/images/evs/ev-ai-images_31.avif':
    '/social/images/evs/ev-ai-images_31-social.jpg',
  '/images/evs/ev-ai-images_32.avif':
    '/social/images/evs/ev-ai-images_32-social.jpg',
  '/images/evs/ev-ai-images_33.avif':
    '/social/images/evs/ev-ai-images_33-social.jpg',
  '/images/evs/ev-ai-images_34.avif':
    '/social/images/evs/ev-ai-images_34-social.jpg',
  '/images/evs/ev-ai-images_35.avif':
    '/social/images/evs/ev-ai-images_35-social.jpg',
  '/images/evs/ev-ai-images_36.avif':
    '/social/images/evs/ev-ai-images_36-social.jpg',
  '/images/evs/ev-ai-images_38.avif':
    '/social/images/evs/ev-ai-images_38-social.jpg',
  '/images/evs/ev-ai-images_39.avif':
    '/social/images/evs/ev-ai-images_39-social.jpg',
  '/images/evs/ev-ai-images_41.avif':
    '/social/images/evs/ev-ai-images_41-social.jpg',
  '/images/evs/ev-ai-images_42.avif':
    '/social/images/evs/ev-ai-images_42-social.jpg',
  '/images/evs/ev-ai-images_43.avif':
    '/social/images/evs/ev-ai-images_43-social.jpg',
  '/images/evs/ev-ai-images_44.avif':
    '/social/images/evs/ev-ai-images_44-social.jpg',
  '/images/evs/ev-ai-images_46.avif':
    '/social/images/evs/ev-ai-images_46-social.jpg',
  '/images/evs/ev-ai-images_47.avif':
    '/social/images/evs/ev-ai-images_47-social.jpg',
  '/images/evs/ev-ai-images_49.avif':
    '/social/images/evs/ev-ai-images_49-social.jpg',
  '/images/evs/ev-ai-images_5.avif':
    '/social/images/evs/ev-ai-images_5-social.jpg',
  '/images/evs/ev-ai-images_50.avif':
    '/social/images/evs/ev-ai-images_50-social.jpg',
  '/images/evs/ev-ai-images_51.avif':
    '/social/images/evs/ev-ai-images_51-social.jpg',
  '/images/evs/ev-ai-images_52.avif':
    '/social/images/evs/ev-ai-images_52-social.jpg',
  '/images/evs/ev-ai-images_53.avif':
    '/social/images/evs/ev-ai-images_53-social.jpg',
  '/images/evs/ev-ai-images_55.avif':
    '/social/images/evs/ev-ai-images_55-social.jpg',
  '/images/evs/ev-ai-images_57.avif':
    '/social/images/evs/ev-ai-images_57-social.jpg',
  '/images/evs/ev-ai-images_58.avif':
    '/social/images/evs/ev-ai-images_58-social.jpg',
  '/images/evs/ev-ai-images_59.avif':
    '/social/images/evs/ev-ai-images_59-social.jpg',
  '/images/evs/ev-ai-images_6.avif':
    '/social/images/evs/ev-ai-images_6-social.jpg',
  '/images/evs/ev-ai-images_60.avif':
    '/social/images/evs/ev-ai-images_60-social.jpg',
  '/images/evs/ev-ai-images_61.avif':
    '/social/images/evs/ev-ai-images_61-social.jpg',
  '/images/evs/ev-ai-images_62.avif':
    '/social/images/evs/ev-ai-images_62-social.jpg',
  '/images/evs/ev-ai-images_63.avif':
    '/social/images/evs/ev-ai-images_63-social.jpg',
  '/images/evs/ev-ai-images_64.avif':
    '/social/images/evs/ev-ai-images_64-social.jpg',
  '/images/evs/ev-ai-images_65.avif':
    '/social/images/evs/ev-ai-images_65-social.jpg',
  '/images/evs/ev-ai-images_66.avif':
    '/social/images/evs/ev-ai-images_66-social.jpg',
  '/images/evs/ev-ai-images_67.avif':
    '/social/images/evs/ev-ai-images_67-social.jpg',
  '/images/evs/ev-ai-images_68.avif':
    '/social/images/evs/ev-ai-images_68-social.jpg',
  '/images/evs/ev-ai-images_69.avif':
    '/social/images/evs/ev-ai-images_69-social.jpg',
  '/images/evs/ev-ai-images_71.avif':
    '/social/images/evs/ev-ai-images_71-social.jpg',
  '/images/evs/ev-ai-images_72.avif':
    '/social/images/evs/ev-ai-images_72-social.jpg',
  '/images/evs/ev-ai-images_73.avif':
    '/social/images/evs/ev-ai-images_73-social.jpg',
  '/images/evs/ev-ai-images_74.avif':
    '/social/images/evs/ev-ai-images_74-social.jpg',
  '/images/evs/ev-ai-images_75.avif':
    '/social/images/evs/ev-ai-images_75-social.jpg',
  '/images/evs/ev-ai-images_76.avif':
    '/social/images/evs/ev-ai-images_76-social.jpg',
  '/images/evs/ev-ai-images_77.avif':
    '/social/images/evs/ev-ai-images_77-social.jpg',
  '/images/evs/ev-ai-images_78.avif':
    '/social/images/evs/ev-ai-images_78-social.jpg',
  '/images/evs/ev-ai-images_79.avif':
    '/social/images/evs/ev-ai-images_79-social.jpg',
  '/images/evs/ev-ai-images_80.avif':
    '/social/images/evs/ev-ai-images_80-social.jpg',
  '/images/evs/ev-ai-images_81.avif':
    '/social/images/evs/ev-ai-images_81-social.jpg',
  '/images/evs/ev-ai-intro-2.avif':
    '/social/images/evs/ev-ai-intro-2-social.jpg',
  '/images/evs/ev-ai-occupants-1.avif':
    '/social/images/evs/ev-ai-occupants-1-social.jpg',
  '/images/evs/ev-ai-occupants-10.avif':
    '/social/images/evs/ev-ai-occupants-10-social.jpg',
  '/images/evs/ev-ai-occupants-11.avif':
    '/social/images/evs/ev-ai-occupants-11-social.jpg',
  '/images/evs/ev-ai-occupants-12.avif':
    '/social/images/evs/ev-ai-occupants-12-social.jpg',
  '/images/evs/ev-ai-occupants-2.avif':
    '/social/images/evs/ev-ai-occupants-2-social.jpg',
  '/images/evs/ev-ai-occupants-3.avif':
    '/social/images/evs/ev-ai-occupants-3-social.jpg',
  '/images/evs/ev-ai-occupants-4.avif':
    '/social/images/evs/ev-ai-occupants-4-social.jpg',
  '/images/evs/ev-ai-occupants-5.avif':
    '/social/images/evs/ev-ai-occupants-5-social.jpg',
  '/images/evs/ev-ai-occupants-6.avif':
    '/social/images/evs/ev-ai-occupants-6-social.jpg',
  '/images/evs/ev-ai-occupants-7.avif':
    '/social/images/evs/ev-ai-occupants-7-social.jpg',
  '/images/evs/ev-ai-occupants-8.avif':
    '/social/images/evs/ev-ai-occupants-8-social.jpg',
  '/images/evs/ev-ai-occupants-9.avif':
    '/social/images/evs/ev-ai-occupants-9-social.jpg',
  '/images/evs/ev-intro.avif': '/social/images/evs/ev-intro-social.jpg',
  '/images/evs/future-of-vehicles-wat.avif':
    '/social/images/evs/future-of-vehicles-wat-social.jpg',
  '/images/good-sheep.avif': '/social/images/good-sheep-social.jpg',
  '/images/grief.avif': '/social/images/grief-social.jpg',
  '/images/guia-practica-padres-conscientes.avif':
    '/social/images/guia-practica-padres-conscientes-social.jpg',
  '/images/guy-fawkes-family-love.avif':
    '/social/images/guy-fawkes-family-love-social.jpg',
  '/images/how-i-view-the-world.avif':
    '/social/images/how-i-view-the-world-social.jpg',
  '/images/i-lose-mia.avif': '/social/images/i-lose-mia-social.jpg',
  '/images/lord-take-us-all.avif': '/social/images/lord-take-us-all-social.jpg',
  '/images/lost-af.avif': '/social/images/lost-af-social.jpg',
  '/images/maslows-hierarchy-of-needs.avif':
    '/social/images/maslows-hierarchy-of-needs-social.jpg',
  '/images/mia-y-yo-anime.avif': '/social/images/mia-y-yo-anime-social.jpg',
  '/images/self-control.avif': '/social/images/self-control-social.jpg',
  '/images/symbols-of-power.avif': '/social/images/symbols-of-power-social.jpg',
  '/images/symbols/dragon-slayer.avif':
    '/social/images/symbols/dragon-slayer-social.jpg',
  '/images/symbols/ma5c.avif': '/social/images/symbols/ma5c-social.jpg',
  '/images/symbols/master-sword.avif':
    '/social/images/symbols/master-sword-social.jpg',
  '/images/symbols/mjolnir.avif': '/social/images/symbols/mjolnir-social.jpg',
  '/images/symbols/narsil.avif': '/social/images/symbols/narsil-social.jpg',
  '/images/symbols/vegvisir.avif': '/social/images/symbols/vegvisir-social.jpg',
  '/images/tcb.avif': '/social/images/tcb-social.jpg',
  '/images/the_internet_is_fucking_weird.avif':
    '/social/images/the_internet_is_fucking_weird-social.jpg',
  '/images/una-nena-poderosa.avif':
    '/social/images/una-nena-poderosa-social.jpg',
  '/images/unclean-one.avif': '/social/images/unclean-one-social.jpg',
  '/images/vs-code-signals.avif': '/social/images/vs-code-signals-social.jpg',
  '/symbols/lightsaber.avif': '/social/symbols/lightsaber-social.jpg',
};
